In [2]:
import pandas as pd
dir_path =r"C:/Users/User/Desktop/msp22059 C-07/msp22059 C-07/2_CSI300_1.5/datasets/"
r_monthly_data = pd.read_csv(dir_path+'(raw)Monthly_data_1.5.csv')
r_monthly_data

,month,inventory,future_return,volume,amount,BASIS,short_balance_ratio,pli,RSI,index_turnover_rate,index_trading_volume,treasury_spread,CCt
0,1,0.887031,NaN,14.172897,9.527357,35.532727,0.000017,0.181818,44.403931,0.561818,9.137233,2.001318,0.0
1,2,0.932187,-0.111051,15.518058,10.760043,28.650850,0.000067,0.450000,40.641425,0.472500,9.481054,1.837575,0.0
2,3,0.943371,-0.044306,15.510125,10.711359,15.828579,0.000131,0.368421,45.810128,0.348947,9.073902,1.638052,0.0
3,4,0.954008,-0.020380,15.835324,11.011147,0.632045,0.000154,0.681818,56.253259,0.454545,9.409949,1.411491,1.0
4,5,0.955730,0.074706,15.756518,11.010782,7.965727,0.000103,0.590909,43.246645,0.560909,9.696019,1.407682,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,149,1.002619,-0.039144,14.564396,10.173585,-4.287357,0.106141,0.391304,54.523974,0.376957,10.924991,1.061322,0.0
149,150,0.999321,-0.043356,14.423992,9.992973,1.493562,0.143683,0.285714,49.217163,0.344286,10.622044,0.957367,0.0
150,151,0.993953,-0.065156,14.359670,9.861994,-1.025756,0.129923,0.312500,45.951869,0.371875,10.459270,0.998850,0.0
151,152,1.003595,0.016296,14.733838,10.250105,6.372923,0.115053,0.545455,65.210494,0.460455,10.864666,0.834641,1.0
152,153,1.003977,0.037407,14.563835,10.123521,10.552464,0.124746,0.545455,47.216694,0.372727,10.664443,0.702168,NaN

In [3]:
#normalize data
cols_to_norm = ['future_return','volume','amount','BASIS','index_turnover_rate','short_balance_ratio','pli','treasury_spread','RSI','index_trading_volume','inventory']
r_monthly_data[cols_to_norm] = r_monthly_data[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
r_monthly_data.head()

,month,inventory,future_return,volume,amount,BASIS,short_balance_ratio,pli,RSI,index_turnover_rate,index_trading_volume,treasury_spread,CCt
0,1,0.000000,NaN,0.358733,0.333202,0.907605,0.000000,0.000000,0.350449,0.197922,0.133184,1.000000,0.0
1,2,0.372442,0.274006,0.608033,0.548687,0.868212,0.000250,0.446382,0.273457,0.149967,0.242066,0.918175,0.0
2,3,0.464685,0.413361,0.606563,0.540177,0.794814,0.000568,0.310596,0.379224,0.083631,0.113128,0.818470,0.0
3,4,0.552416,0.463314,0.666832,0.592582,0.707826,0.000683,0.832237,0.592920,0.140327,0.219548,0.705253,1.0
4,5,0.566625,0.661840,0.652227,0.592519,0.749805,0.000430,0.680921,0.326768,0.197434,0.310142,0.703350,0.0

In [4]:
r_monthly_data = r_monthly_data.dropna()
r_monthly_data = r_monthly_data.drop(['month'], axis=1)
r_monthly_data

,inventory,future_return,volume,amount,BASIS,short_balance_ratio,pli,RSI,index_turnover_rate,index_trading_volume,treasury_spread,CCt
1,0.372442,0.274006,0.608033,0.548687,0.868212,0.000250,0.446382,0.273457,0.149967,0.242066,0.918175,0.0
2,0.464685,0.413361,0.606563,0.540177,0.794814,0.000568,0.310596,0.379224,0.083631,0.113128,0.818470,0.0
3,0.552416,0.463314,0.666832,0.592582,0.707826,0.000683,0.832237,0.592920,0.140327,0.219548,0.705253,1.0
4,0.566625,0.661840,0.652227,0.592519,0.749805,0.000430,0.680921,0.326768,0.197434,0.310142,0.703350,0.0
5,0.519371,0.529192,0.562829,0.510225,0.775211,0.000341,0.573407,0.479581,0.193272,0.294931,0.719495,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
147,0.948127,0.525397,0.454516,0.475328,0.598702,0.486567,0.410714,0.061068,0.129449,0.711594,0.553539,0.0
148,0.953362,0.424139,0.431290,0.446169,0.679666,0.530229,0.348684,0.557534,0.098669,0.699337,0.530268,0.0
149,0.926157,0.415344,0.405269,0.414596,0.712757,0.717801,0.172932,0.448942,0.081128,0.603399,0.478320,0.0
150,0.881882,0.369829,0.393348,0.391700,0.698336,0.649050,0.217516,0.382124,0.095941,0.551851,0.499050,0.0
151,0.961409,0.539889,0.462693,0.459545,0.740688,0.574755,0.605263,0.776211,0.143500,0.680233,0.416991,1.0

In [5]:
# Processing unbalanced dataset:ã€€SMOTE
from imblearn.over_sampling import SMOTE
from sklearn.datasets import make_classification
from sklearn.metrics import recall_score, roc_auc_score

In [6]:
X = r_monthly_data.iloc[:, :-1]  # Features (all columns except the last one)
y = r_monthly_data.iloc[:, -1]   # Labels (last column)
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
balanced_df = pd.concat([X_resampled, y_resampled], axis=1)

In [7]:
balanced_df

,inventory,future_return,volume,amount,BASIS,short_balance_ratio,pli,RSI,index_turnover_rate,index_trading_volume,treasury_spread,CCt
0,0.372442,0.274006,0.608033,0.548687,0.868212,0.000250,0.446382,0.273457,0.149967,0.242066,0.918175,0.0
1,0.464685,0.413361,0.606563,0.540177,0.794814,0.000568,0.310596,0.379224,0.083631,0.113128,0.818470,0.0
2,0.552416,0.463314,0.666832,0.592582,0.707826,0.000683,0.832237,0.592920,0.140327,0.219548,0.705253,1.0
3,0.566625,0.661840,0.652227,0.592519,0.749805,0.000430,0.680921,0.326768,0.197434,0.310142,0.703350,0.0
4,0.519371,0.529192,0.562829,0.510225,0.775211,0.000341,0.573407,0.479581,0.193272,0.294931,0.719495,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
243,0.598013,0.581121,0.116786,0.126498,0.452611,0.046547,0.731641,0.444834,0.167901,0.498184,0.379941,1.0
244,0.952411,0.445790,0.451790,0.468845,0.563824,0.520085,0.598019,0.453227,0.171814,0.686888,0.472229,1.0
245,0.951269,0.476154,0.465108,0.501370,0.655678,0.580547,0.407513,0.620996,0.303819,0.798083,0.339702,1.0
246,0.613608,0.316601,0.328937,0.300250,0.090029,0.025044,0.606690,0.317793,0.265181,0.556012,0.492309,1.0
247,0.962315,0.441315,0.467142,0.508135,0.512248,0.614901,0.453812,0.554090,0.261890,0.847368,0.435163,1.0

In [8]:
print("Class distribution before SMOTE:")
print(r_monthly_data.iloc[:, -1].value_counts())
print("\nClass distribution after SMOTE:")
print(balanced_df.iloc[:, -1].value_counts())

Class distribution before SMOTE:
0.0    124
1.0     27
Name: CCt, dtype: int64

Class distribution after SMOTE:
0.0    124
1.0    124
Name: CCt, dtype: int64

In [12]:
# Using balanced df to make predictions
# Model 1, logistic regression

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import  accuracy_score, recall_score, roc_auc_score, f1_score

X = balanced_df.iloc[:, :-1]  # Features (all columns except the last one)
y = balanced_df.iloc[:, -1]   # Labels (last column)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=28)

# Create a logistic regression model
logreg = LogisticRegression(C=0.1, solver='liblinear', random_state=28)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Make predictions on the test data
y_pred = logreg.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)

# Calculate the recall
recall = recall_score(y_test, y_pred)

# Calculate the ROC-AUC
roc_auc = roc_auc_score(y_test, y_pred)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)

# Print the merics
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("F1 score:", f1)
print("Recall:", recall)

Accuracy: 0.6
ROC-AUC: 0.6166666666666666
F1 score: 0.6153846153846153
Recall: 0.5333333333333333