In [1]:
import pandas as pd
dir_path =r"C:/Users/User/Desktop/msp22059 C-07/msp22059 C-07/2_CSI300_1.5/datasets/"
r_weekly_data = pd.read_csv(dir_path+'(raw)Weekly_data_1.5.csv')

In [2]:
r_weekly_data.head()

,week,future_return,volume,inventory,amount,BASIS,index_turnover_rate,short_balance_ratio,pli,t_spread,RSI,index_trading_volume,CCt+1
0,1,NaN,10.976047,8.185907,6.405856,59.2680,0.440,0.000005,0.00,2.04740,0.000000,6.510794,0.0
1,2,-0.056701,13.400486,10.345831,8.768549,31.7160,0.658,0.000010,0.20,2.01880,52.442353,8.499683,0.0
2,3,-0.028819,13.474156,10.799555,8.809270,34.6024,0.490,0.000027,0.20,1.97462,18.350791,8.218636,0.0
3,4,-0.042739,13.527370,10.820138,8.819118,57.0780,0.500,0.000028,0.25,1.94245,17.038370,7.993090,0.0
4,5,-0.048364,14.049264,11.179381,9.294620,16.1712,0.468,0.000056,0.60,1.89940,48.441850,8.089973,1.0

In [3]:
#normalize data
cols_to_norm = ['future_return','volume','amount','BASIS','index_turnover_rate','short_balance_ratio','pli','t_spread','RSI','index_trading_volume','inventory']
r_weekly_data[cols_to_norm] = r_weekly_data[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
r_weekly_data.head()

,week,future_return,volume,inventory,amount,BASIS,index_turnover_rate,short_balance_ratio,pli,t_spread,RSI,index_trading_volume,CCt+1
0,1,NaN,0.264808,0.000000,0.261012,0.927600,0.119796,0.000000,0.00,1.000000,0.000000,0.069764,0.0
1,2,0.487179,0.592076,0.368713,0.570826,0.865631,0.212404,0.000022,0.20,0.987335,0.524424,0.525772,0.0
2,3,0.569215,0.602021,0.446166,0.576166,0.872123,0.141037,0.000102,0.20,0.967770,0.183508,0.461334,0.0
3,4,0.528259,0.609204,0.449680,0.577457,0.922674,0.145285,0.000108,0.25,0.953524,0.170384,0.409622,0.0
4,5,0.511708,0.679653,0.511005,0.639809,0.830668,0.131691,0.000235,0.60,0.934460,0.484418,0.431835,1.0

In [4]:
r_weekly_data = r_weekly_data.dropna()
r_weekly_data = r_weekly_data.drop(['week'], axis=1)

In [5]:
# Processing unbalanced dataset:　SMOTE
from imblearn.over_sampling import SMOTE
from sklearn.datasets import make_classification
from sklearn.metrics import recall_score, roc_auc_score

In [6]:
X = r_weekly_data.iloc[:, :-1]  # Features (all columns except the last one)
y = r_weekly_data.iloc[:, -1]   # Labels (last column)
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
balanced_df = pd.concat([X_resampled, y_resampled], axis=1)

In [7]:

balanced_df

,future_return,volume,inventory,amount,BASIS,index_turnover_rate,short_balance_ratio,pli,t_spread,RSI,index_trading_volume,CCt+1
0,0.487179,0.592076,0.368713,0.570826,0.865631,0.212404,0.000022,0.200000,0.987335,0.524424,0.525772,0.0
1,0.569215,0.602021,0.446166,0.576166,0.872123,0.141037,0.000102,0.200000,0.967770,0.183508,0.461334,0.0
2,0.528259,0.609204,0.449680,0.577457,0.922674,0.145285,0.000108,0.250000,0.953524,0.170384,0.409622,0.0
3,0.511708,0.679653,0.511005,0.639809,0.830668,0.131691,0.000235,0.600000,0.934460,0.484418,0.431835,1.0
4,0.563284,0.703962,0.530620,0.659014,0.855181,0.123195,0.000378,0.400000,0.884720,0.428781,0.409571,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1049,0.587290,0.360292,0.692219,0.341913,0.603917,0.199091,0.024274,0.453890,0.555096,0.455598,0.641083,1.0
1050,0.517006,0.591679,0.959728,0.602168,0.784000,0.166590,0.579561,0.200000,0.523639,0.299373,0.778145,1.0
1051,0.656764,0.559959,0.947382,0.561564,0.784241,0.076469,0.610342,0.200000,0.534896,0.154390,0.687144,1.0
1052,0.650764,0.341781,0.686135,0.355715,0.761764,0.113968,0.055579,0.375726,0.353322,0.455172,0.620145,1.0
1053,0.641734,0.553312,0.960465,0.581748,0.746088,0.165768,0.556507,0.800000,0.494121,0.309351,0.780784,1.0

In [8]:
print("Class distribution before SMOTE:")
print(r_weekly_data.iloc[:, -1].value_counts())
print("\nClass distribution after SMOTE:")
print(balanced_df.iloc[:, -1].value_counts())

Class distribution before SMOTE:
0.0    527
1.0    123
Name: CCt+1, dtype: int64

Class distribution after SMOTE:
0.0    527
1.0    527
Name: CCt+1, dtype: int64

In [9]:
# Using balanced df to make predictions
# Model 1, logistic regression

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import  accuracy_score, recall_score, roc_auc_score, f1_score

X = balanced_df.iloc[:, :-1]  # Features (all columns except the last one)
y = balanced_df.iloc[:, -1]   # Labels (last column)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# Create a logistic regression model
logreg = LogisticRegression(solver='liblinear', C=0.4, random_state=42)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Make predictions on the test data
y_pred = logreg.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)

# Calculate the recall
recall = recall_score(y_test, y_pred)

# Calculate the ROC-AUC
roc_auc = roc_auc_score(y_test, y_pred)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)

# Print the merics
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("F1 score:", f1)
print("Recall:", recall)

Accuracy: 0.6255924170616114
ROC-AUC: 0.6250224860586436
F1 score: 0.6108374384236452
Recall: 0.6078431372549019