In [1]:
import pandas as pd
dir_path =r"C:/Users/Laura/Desktop/msp22059 C-07/msp22059 C-07/3_robustness_test_1.5/datasets/"
df=pd.read_csv(dir_path+'500_data_monthly_1.5.csv')

In [2]:
df

,m,volume,closingPrice,amount,BASIS,inventory,short_balance_ratio,RSI,pli,camount,turnoverRatio,spread,CCt+1
0,1,14.201869,NaN,10.077930,-139.062727,12.144915,0.006269,37.881327,0.800000,10.370347,4.360909,0.496676,0.0
1,2,15.327183,0.112933,11.343842,-28.476500,13.474522,0.005209,47.792163,0.700000,11.047016,4.115500,1.013475,1.0
2,3,15.829562,0.134180,11.949884,-164.501905,13.832623,0.004078,39.356259,0.523810,11.223600,4.269048,1.740671,1.0
3,4,15.343232,-0.339026,11.159442,-325.186522,13.062730,0.002590,43.366599,0.478261,10.860472,3.550000,1.322817,1.0
4,5,14.903162,-0.005283,10.684692,-362.787619,12.905038,0.003500,42.384784,0.476190,10.632604,3.005238,1.241205,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,14.614080,-0.000160,10.234516,-25.123043,15.806881,0.106141,42.622897,0.521739,10.482733,1.157391,1.061322,1.0
89,90,14.583571,-0.045850,10.162973,-14.769048,15.717310,0.143683,38.808999,0.428571,10.080702,0.933810,0.957367,0.0
90,91,14.403126,-0.024630,9.958466,-1.910625,15.466114,0.129923,48.493263,0.562500,9.903985,0.925000,0.998850,0.0
91,92,14.543896,0.041309,10.138870,9.376818,15.750296,0.115053,76.866086,0.409091,10.408075,1.094545,0.834641,0.0
92,93,14.363599,-0.016284,9.949398,13.076364,15.719227,0.124746,47.819403,0.318182,10.217406,0.913182,0.702168,NaN

In [3]:
#normalize data
cols_to_norm = df.columns[:-1]
df[cols_to_norm] = df[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
df.head()

,m,volume,closingPrice,amount,BASIS,inventory,short_balance_ratio,RSI,pli,camount,turnoverRatio,spread,CCt+1
0,0.000000,0.567252,NaN,0.562754,0.595228,0.000000,0.018621,0.198145,1.000000,0.606984,1.000000,0.285260,0.0
1,0.010870,0.866435,0.942467,0.858442,0.889447,0.362582,0.013255,0.371367,0.808511,0.918664,0.932093,0.582188,1.0
2,0.021739,1.000000,0.986774,1.000000,0.527546,0.460235,0.007528,0.223924,0.471125,1.000000,0.974581,1.000000,1.0
3,0.032609,0.870702,0.000000,0.815370,0.100039,0.250287,0.000000,0.294017,0.383904,0.832740,0.775614,0.759921,1.0
4,0.043478,0.753702,0.695954,0.704479,0.000000,0.207284,0.004606,0.276856,0.379939,0.727782,0.624874,0.713030,1.0

In [4]:
#use SVM
from sklearn import svm
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import  accuracy_score, recall_score, roc_auc_score, f1_score

In [6]:
#drop NaN
df = df.dropna()
#drop week column
df = df.drop(['m'], axis=1)

In [7]:
from imblearn.over_sampling import SMOTE
X = df.iloc[:, :-1]  # Features (all columns except the last one)
y = df.iloc[:, -1]   # Labels (last column)
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
balanced_df = pd.concat([X_resampled, y_resampled], axis=1)

In [8]:
balanced_df

,volume,closingPrice,amount,BASIS,inventory,short_balance_ratio,RSI,pli,camount,turnoverRatio,spread,CCt+1
0,0.866435,0.942467,0.858442,0.889447,0.362582,0.013255,0.371367,0.808511,0.918664,0.932093,0.582188,1.0
1,1.000000,0.986774,1.000000,0.527546,0.460235,0.007528,0.223924,0.471125,1.000000,0.974581,1.000000,1.0
2,0.870702,0.000000,0.815370,0.100039,0.250287,0.000000,0.294017,0.383904,0.832740,0.775614,0.759921,1.0
3,0.753702,0.695954,0.704479,0.000000,0.207284,0.004606,0.276856,0.379939,0.727782,0.624874,0.713030,1.0
4,0.271301,0.264952,0.219762,0.326460,0.111944,0.014044,0.203496,0.521277,0.462256,0.402473,0.594796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
143,0.156057,0.511466,0.105560,0.869321,0.400748,0.080195,0.447512,0.061558,0.120698,0.000979,0.302136,1.0
144,0.908112,0.285510,0.868791,0.223733,0.311033,0.002178,0.273736,0.409140,0.881135,0.833183,0.829385,1.0
145,0.198092,0.627880,0.135693,0.894390,0.442346,0.084342,0.317776,0.512573,0.224755,0.034476,0.374436,1.0
146,0.137828,0.658306,0.089758,0.910404,0.377068,0.085607,0.330117,0.359115,0.156551,0.043320,0.486508,1.0
147,0.701329,0.577765,0.612208,0.907533,0.963118,0.487373,0.280244,0.313248,0.586490,0.204394,0.441644,1.0

In [35]:
X = balanced_df.iloc[:, :-1]  # Features (all columns except the last one)
y = balanced_df.iloc[:, -1]   # Labels (last column)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [36]:
#fit SVM model
clf = svm.SVC(kernel='linear', C=0.8, random_state=3).fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [37]:
#accuracy
print("Accuracy:",accuracy_score(y_test, y_pred))
roc_auc = roc_auc_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
print("ROC-AUC:", roc_auc)
print("recall:",recall)
#confusion matrix
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
#classification report
print("Classification Report:\n",classification_report(y_test, y_pred))

Accuracy: 0.6333333333333333
ROC-AUC: 0.6527777777777778
recall: 0.5555555555555556
Confusion Matrix:
 [[ 9  3]
 [ 8 10]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.53      0.75      0.62        12
         1.0       0.77      0.56      0.65        18

    accuracy                           0.63        30
   macro avg       0.65      0.65      0.63        30
weighted avg       0.67      0.63      0.64        30