In [4]:
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.metrics import  accuracy_score, recall_score, roc_auc_score, f1_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import ComplementNB, GaussianNB, CategoricalNB, BernoulliNB, MultinomialNB

In [5]:
dir_path =r"C:/Users/Laura/Desktop/msp22059 C-07/msp22059 C-07/3_robustness_test_1.5/datasets/"
df=pd.read_csv(dir_path+'50_data_monthly_1.5.csv')

In [7]:
#normalize data
cols_to_norm = df.columns[:-1]
df[cols_to_norm] = df[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
df.head()

,month,closingPrice,volume,amount,BASIS,inventory,short_balance_ratio,RSI,pli,camount,turnoverRatio,spread,CCt+1
0,0.000000,NaN,0.715039,0.742039,1.000000,0.253679,0.018621,0.625067,0.349823,0.841994,1.000000,0.285260,0.0
1,0.010870,0.501544,0.857958,0.871737,0.917001,0.556260,0.013255,0.349212,0.349823,0.918760,0.637128,0.582188,0.0
2,0.021739,0.563078,1.000000,1.000000,0.860105,0.792546,0.007528,0.378333,0.307252,0.992414,0.753267,1.000000,1.0
3,0.032609,0.000000,0.954749,0.927285,0.058075,0.494215,0.000000,0.662400,0.000000,1.000000,0.759711,0.759921,1.0
4,0.043478,0.141392,0.854675,0.803065,0.000000,0.336988,0.004606,0.333955,0.307252,0.684446,0.329025,0.713030,1.0

In [8]:
df = df.dropna()
df = df.drop(['month'], axis=1)
df

,closingPrice,volume,amount,BASIS,inventory,short_balance_ratio,RSI,pli,camount,turnoverRatio,spread,CCt+1
1,0.501544,0.857958,0.871737,0.917001,0.556260,0.013255,0.349212,0.349823,0.918760,0.637128,0.582188,0.0
2,0.563078,1.000000,1.000000,0.860105,0.792546,0.007528,0.378333,0.307252,0.992414,0.753267,1.000000,1.0
3,0.000000,0.954749,0.927285,0.058075,0.494215,0.000000,0.662400,0.000000,1.000000,0.759711,0.759921,1.0
4,0.141392,0.854675,0.803065,0.000000,0.336988,0.004606,0.333955,0.307252,0.684446,0.329025,0.713030,1.0
5,0.323795,0.382338,0.344200,0.005320,0.136381,0.014044,0.265914,0.439223,0.474368,0.192031,0.594796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
87,0.589703,0.540892,0.556679,0.583744,0.870375,0.479881,0.122975,0.051826,0.568484,0.137641,0.636434,0.0
88,0.420020,0.540197,0.545821,0.747506,0.935115,0.524112,0.643508,0.155477,0.533596,0.090227,0.609678,0.0
89,0.500876,0.534363,0.536253,0.765540,0.963536,0.714126,0.409065,0.051826,0.444782,0.085630,0.549950,1.0
90,0.315885,0.535400,0.520756,0.721563,0.878152,0.644480,0.095655,0.014576,0.414919,0.102797,0.573785,0.0
91,0.634924,0.608449,0.591122,0.767229,0.995078,0.569218,0.944179,0.349823,0.556135,0.141086,0.479438,0.0

In [9]:
X = df.iloc[:, :-1]  # Features (all columns except the last one)
y = df.iloc[:, -1]   # Labels (last column)
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
balanced_df = pd.concat([X_resampled, y_resampled], axis=1)

In [10]:
#balanced_df.to_csv("balanced_df_weekly.csv")
balanced_df

,closingPrice,volume,amount,BASIS,inventory,short_balance_ratio,RSI,pli,camount,turnoverRatio,spread,CCt+1
0,0.501544,0.857958,0.871737,0.917001,0.556260,0.013255,0.349212,0.349823,0.918760,0.637128,0.582188,0.0
1,0.563078,1.000000,1.000000,0.860105,0.792546,0.007528,0.378333,0.307252,0.992414,0.753267,1.000000,1.0
2,0.000000,0.954749,0.927285,0.058075,0.494215,0.000000,0.662400,0.000000,1.000000,0.759711,0.759921,1.0
3,0.141392,0.854675,0.803065,0.000000,0.336988,0.004606,0.333955,0.307252,0.684446,0.329025,0.713030,1.0
4,0.323795,0.382338,0.344200,0.005320,0.136381,0.014044,0.265914,0.439223,0.474368,0.192031,0.594796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
149,0.574440,0.329823,0.360839,0.757841,0.402093,0.069396,0.237731,0.313408,0.354138,0.076227,0.488206,1.0
150,0.561447,0.542777,0.590386,0.559278,0.819423,0.718891,0.320975,0.213545,0.628029,0.104106,0.529503,1.0
151,0.384345,0.399979,0.412486,0.509865,0.274883,0.035623,0.267152,0.276149,0.461597,0.134955,0.408333,1.0
152,0.394347,0.435010,0.454774,0.616407,0.588452,0.048139,0.390279,0.261940,0.523617,0.124631,0.551201,1.0
153,0.374250,0.598733,0.628980,0.526235,0.816120,0.582508,0.059616,0.345249,0.716443,0.143322,0.569095,1.0

In [14]:
# Using balanced df to make predictions
X = df.iloc[:, :-1]  # Features (all columns except the last one)
y = df.iloc[:, -1]   # Labels (last column)

X = balanced_df.iloc[:, :-1]
y = balanced_df.iloc[:, -1]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=8)

In [15]:
gnb = GaussianNB().fit(X_train, y_train)
prediction = gnb.predict(X_test)  # predictions
prediction_train = gnb.predict(X_train)

accuracy = accuracy_score(y_test, prediction)
recall = recall_score(y_test, prediction)
roc_auc = roc_auc_score(y_test, prediction)
f1 = f1_score(y_test, prediction)
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("F1 score:", f1)
print("Recall:", recall)

Accuracy: 0.723404255319149
ROC-AUC: 0.7290909090909091
F1 score: 0.7111111111111111
Recall: 0.64