In [3]:
import pandas as pd
dir_path =r"C:/Users/Laura/Desktop/msp22059 C-07/msp22059 C-07/3_robustness_test_1.5/datasets/"
r_monthly_data = pd.read_csv(dir_path+'50_data_monthly_1.5.csv')
r_monthly_data

,month,closingPrice,volume,amount,BASIS,inventory,short_balance_ratio,RSI,pli,camount,turnoverRatio,spread,CCt+1
0,1,NaN,14.861329,10.237230,19.801818,13.145783,0.006269,57.038993,0.500000,10.389480,1.501818,0.496676,0.0
1,2,-0.025736,15.552497,10.909668,13.579000,13.829907,0.005209,43.925584,0.500000,10.600157,0.993500,1.013475,0.0
2,3,-0.007201,16.239423,11.574667,9.313333,14.364144,0.004078,45.309926,0.476190,10.802293,1.156190,1.740671,1.0
3,4,-0.176809,16.020588,11.197667,-50.818261,13.689626,0.002590,58.813699,0.304348,10.823113,1.165217,1.322817,1.0
4,5,-0.134219,15.536621,10.553627,-55.172381,13.334140,0.003500,43.200322,0.476190,9.957105,0.561905,1.241205,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,-0.050292,14.015779,9.219909,0.871304,14.686487,0.106141,57.915629,0.391304,9.543109,0.227391,1.061322,0.0
89,90,-0.025937,13.987566,9.170302,2.223333,14.750747,0.143683,46.770829,0.333333,9.299369,0.220952,0.957367,1.0
90,91,-0.081659,13.992582,9.089955,-1.073750,14.557696,0.129923,31.872192,0.312500,9.217412,0.245000,0.998850,0.0
91,92,0.014440,14.345853,9.454781,2.350000,14.822063,0.115053,72.208717,0.500000,9.604966,0.298636,0.834641,0.0
92,93,0.055866,14.205217,9.375656,5.240000,14.833191,0.124746,44.314418,0.590909,9.366314,0.225909,0.702168,NaN

In [6]:
#normalize data
cols_to_norm = r_monthly_data.columns[:-1]
r_monthly_data[cols_to_norm] = r_monthly_data[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
r_monthly_data.head()

,month,closingPrice,volume,amount,BASIS,inventory,short_balance_ratio,RSI,pli,camount,turnoverRatio,spread,CCt+1
0,0.000000,NaN,0.715039,0.742039,1.000000,0.253679,0.018621,0.625067,0.349823,0.841994,1.000000,0.285260,0.0
1,0.010870,0.501544,0.857958,0.871737,0.917001,0.556260,0.013255,0.349212,0.349823,0.918760,0.637128,0.582188,0.0
2,0.021739,0.563078,1.000000,1.000000,0.860105,0.792546,0.007528,0.378333,0.307252,0.992414,0.753267,1.000000,1.0
3,0.032609,0.000000,0.954749,0.927285,0.058075,0.494215,0.000000,0.662400,0.000000,1.000000,0.759711,0.759921,1.0
4,0.043478,0.141392,0.854675,0.803065,0.000000,0.336988,0.004606,0.333955,0.307252,0.684446,0.329025,0.713030,1.0

In [7]:
r_monthly_data = r_monthly_data.dropna()
r_monthly_data = r_monthly_data.drop(['month'], axis=1)
r_monthly_data

,closingPrice,volume,amount,BASIS,inventory,short_balance_ratio,RSI,pli,camount,turnoverRatio,spread,CCt+1
1,0.501544,0.857958,0.871737,0.917001,0.556260,0.013255,0.349212,0.349823,0.918760,0.637128,0.582188,0.0
2,0.563078,1.000000,1.000000,0.860105,0.792546,0.007528,0.378333,0.307252,0.992414,0.753267,1.000000,1.0
3,0.000000,0.954749,0.927285,0.058075,0.494215,0.000000,0.662400,0.000000,1.000000,0.759711,0.759921,1.0
4,0.141392,0.854675,0.803065,0.000000,0.336988,0.004606,0.333955,0.307252,0.684446,0.329025,0.713030,1.0
5,0.323795,0.382338,0.344200,0.005320,0.136381,0.014044,0.265914,0.439223,0.474368,0.192031,0.594796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
87,0.589703,0.540892,0.556679,0.583744,0.870375,0.479881,0.122975,0.051826,0.568484,0.137641,0.636434,0.0
88,0.420020,0.540197,0.545821,0.747506,0.935115,0.524112,0.643508,0.155477,0.533596,0.090227,0.609678,0.0
89,0.500876,0.534363,0.536253,0.765540,0.963536,0.714126,0.409065,0.051826,0.444782,0.085630,0.549950,1.0
90,0.315885,0.535400,0.520756,0.721563,0.878152,0.644480,0.095655,0.014576,0.414919,0.102797,0.573785,0.0
91,0.634924,0.608449,0.591122,0.767229,0.995078,0.569218,0.944179,0.349823,0.556135,0.141086,0.479438,0.0

In [8]:
# Processing unbalanced dataset:ã€€SMOTE
from imblearn.over_sampling import SMOTE
from sklearn.datasets import make_classification
from sklearn.metrics import recall_score, roc_auc_score

In [9]:
X = r_monthly_data.iloc[:, :-1]  # Features (all columns except the last one)
y = r_monthly_data.iloc[:, -1]   # Labels (last column)
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
balanced_df = pd.concat([X_resampled, y_resampled], axis=1)

In [10]:
balanced_df

,closingPrice,volume,amount,BASIS,inventory,short_balance_ratio,RSI,pli,camount,turnoverRatio,spread,CCt+1
0,0.501544,0.857958,0.871737,0.917001,0.556260,0.013255,0.349212,0.349823,0.918760,0.637128,0.582188,0.0
1,0.563078,1.000000,1.000000,0.860105,0.792546,0.007528,0.378333,0.307252,0.992414,0.753267,1.000000,1.0
2,0.000000,0.954749,0.927285,0.058075,0.494215,0.000000,0.662400,0.000000,1.000000,0.759711,0.759921,1.0
3,0.141392,0.854675,0.803065,0.000000,0.336988,0.004606,0.333955,0.307252,0.684446,0.329025,0.713030,1.0
4,0.323795,0.382338,0.344200,0.005320,0.136381,0.014044,0.265914,0.439223,0.474368,0.192031,0.594796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
149,0.574440,0.329823,0.360839,0.757841,0.402093,0.069396,0.237731,0.313408,0.354138,0.076227,0.488206,1.0
150,0.561447,0.542777,0.590386,0.559278,0.819423,0.718891,0.320975,0.213545,0.628029,0.104106,0.529503,1.0
151,0.384345,0.399979,0.412486,0.509865,0.274883,0.035623,0.267152,0.276149,0.461597,0.134955,0.408333,1.0
152,0.394347,0.435010,0.454774,0.616407,0.588452,0.048139,0.390279,0.261940,0.523617,0.124631,0.551201,1.0
153,0.374250,0.598733,0.628980,0.526235,0.816120,0.582508,0.059616,0.345249,0.716443,0.143322,0.569095,1.0

In [11]:
print("Class distribution before SMOTE:")
print(r_monthly_data.iloc[:, -1].value_counts())
print("\nClass distribution after SMOTE:")
print(balanced_df.iloc[:, -1].value_counts())

Class distribution before SMOTE:
0.0    77
1.0    14
Name: CCt+1, dtype: int64

Class distribution after SMOTE:
0.0    77
1.0    77
Name: CCt+1, dtype: int64

In [12]:
# Using balanced df to make predictions
# Model 1, logistic regression

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import  accuracy_score, recall_score, roc_auc_score, f1_score

X = balanced_df.iloc[:, :-1]  # Features (all columns except the last one)
y = balanced_df.iloc[:, -1]   # Labels (last column)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=28)

# Create a logistic regression model
logreg = LogisticRegression(C=0.1, solver='liblinear', random_state=28)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Make predictions on the test data
y_pred = logreg.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)

# Calculate the recall
recall = recall_score(y_test, y_pred)

# Calculate the ROC-AUC
roc_auc = roc_auc_score(y_test, y_pred)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)

# Print the merics
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("F1 score:", f1)
print("Recall:", recall)

Accuracy: 0.5806451612903226
ROC-AUC: 0.58125
F1 score: 0.5806451612903225
Recall: 0.5625